### ISSUE TITLE
Question: Updated typhen to TS 1.6.2 - new branch ?

### ISSUE THREAD

**Issue by sebilasse** [shiwano/typhen#1]
Hey there,

by the help of https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes I just updated this nice project to support the recent TypeScript version.

I think it needs testing - how should I make a PR? Could you make a branch?

hints for other projects < 1.5:
- all occurrences of 'filename' in the TS API are camelCased now which conforms to the method names
  - `filename`(s) --> `fileName`(s)
- `getEnumMemberValue` --> `getConstantValue`
- `getLineAndCharacterFromPosition` --> `getLineAndCharacterOfPosition`
- `ts.getPreEmitDiagnostics(this.program);` basically catches all the errors

[edit]
- `ts.SymbolFlags.Import` --> `ts.SymbolFlags.Merged`

**Comment by shiwano** [comment]
Thank you for your help, @sebilasse :-)

I made the `typescript-1.6.2` branch for testing the recent TypeScript version.
Could you make a PR for this branch?

**Comment by sebilasse** [comment]
@shiwano 
Yes - there seem to be some more changes in 1.6 to 1.6.2 - they made some APIs internal and now `ResolvedType` is missing in the API and `.symbol` is missing in the `Node` Interface of the API. I raised another issue at TS - they are already aware of it and now exposed some APIs which were internal in the meantime - let's see how they answer.
Maybe a better way would be to use https://github.com/TypeStrong/ntypescript which already makes the '@internal' s public - don't know - would like to see a consistent official TS API ;)

**Comment by shiwano** [comment]
> Maybe a better way would be to use https://github.com/TypeStrong/ntypescript which already makes the '@internal' s public - don't know - would like to see a consistent official TS API ;)

Right, it's looks good to me too.

**Comment by sebilasse** [comment]
@shiwano ok. it seem they corrected it, so we can use the official API.
Just a few more constants were renamed - will edit the above post and work on it now ...

**Comment by shiwano** [comment]
Hi, @sebilasse. I would like to know what the situation of your work. If you make a WIP PR, maybe I could help you, how is it? :-)

**Comment by sebilasse** [comment]
Hi, @shiwano.
Ran into kind of a "hardware disaster" on a journey. However: 
Just made the WIP PR, the problem basically is that I can't find anything in the 1.6.x API where I can get the "resolved model" (with extends etc. ...).

**Comment by shiwano** [comment]
Thank you so much, @sebilasse !
I will checkout the PR, and look into the problem if possible. :smiley:

**Comment by shiwano** [comment]
It tentatively works with TypeScript v1.6.2. https://github.com/shiwano/typhen/pull/3

**Comment by sebilasse** [comment]
@shiwano :+1: 
Thanks so much. 
Just one question : How about a new version number in the package.json / for npm, e.g. 
`"version": "0.4.2"` (or 0.5.0) ...

**Comment by shiwano** [comment]
For sure, I've published a new version as `0.6.0` ! :smile:
